# Generated by Django 4.0.4 on 2022-04-19 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter project title', max_length=100)),
                ('user', models.ManyToManyField(blank=True, help_text='Assign user to this project', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(help_text='Enter task name', max_length=100)),
                ('task_description', models.CharField(blank=True, help_text='Enter task description', max_length=200)),
                ('due_date', models.DateField()),
                ('files', models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/%d')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.project')),
                ('user', models.ManyToManyField(blank=True, help_text='Assign user to this task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
