# Generated by Django 4.0.4 on 2022-04-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='project',
            field=models.ManyToManyField(help_text='Assign project for team member', to='tasks.project'),
        ),
        migrations.AlterField(
            model_name='team',
            name='task',
            field=models.ManyToManyField(help_text='Assign task for team member', to='tasks.task'),
        ),
    ]
